select * 
from customer_shopping 
limit 20;

----> 1. What is the total revenue generated by male and female customer ?

select sum(purchese_amount),gender
from customer_shopping
group by gender;


----->2. Which customer used a discount but still spent more then avearge purchese amount ?
select customer_id,purchese_amount
from customer_shopping 
where discount_applied = 'Yes'  and 
      purchese_amount > (select avg(purchese_amount)
	                     from customer_shopping);


select count(customer_id),sum(purchese_amount)
from customer_shopping 
where discount_applied = 'Yes'  and 
      purchese_amount > (select avg(purchese_amount)
	                     from customer_shopping);

-- > 3. Which of the top 5 products with the highest avg review rating
-- select category ,review_rating 
-- from (select ROWNUM()AS SLNO, CUSTOMER_SHOPPING.*
--       FROM (SELECT DISTINCT(PURCHESE_AMOUNT)
-- 	         FROM CUSTOMER_BEHAVIOR 
-- 			 ORDER BY PURCHESE_AMOUNT DESC))
-- WHERE SLNO=5;

--1. 
select item_purchased, avg(review_rating) 
from customer_shopping 
group by item_purchased
order by avg(review_rating) desc
limit  5;


-- 2. 
select category, avg(review_rating) as avg_rating
from customer_shopping
group by category
order by avg_rating desc
limit 5 ;	

-- 3.
with rating as (
                select category,avg(review_rating) as avg_rating
                from customer_shopping 
				group by category 
				)
select *
from rating 
order by avg_rating 
limit 5;

-- -->4. Compaire the avg purchese amounts between standard and express shipping 

select shipping_type,round(avg(purchese_amount),2)
from customer_shopping 
where shipping_type in ('Standard','Express')
group by shipping_type;


-- --> 5. Do subscribed customer spend more? compare average spend and revenue 
--  between subscribers and non subscribers 

select count(customer_id),
subscription_status, 
round(avg(purchese_amount),2) as "avg_spend", 
round(sum(purchese_amount),2) as "total_revenue"
from customer_shopping
group by subscription_status
order by total_revenue,avg_spend desc;


-- 6. which 5 product have the highest percentage of purchases with discounts applied? 

select item_purchased, 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customer_shopping 
group by item_purchased
order by discount_rate desc
limit 5;


-- --> 7. Segment customers into new,returning, loyal based on their total number of previous and show the count 
-- of each segment 

with customer_type as (
select customer_id,previous_purchases,
case 
    when previous_purchases = 1 then 'New'
	when previous_purchases  between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_shopping
)

select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment;



-- > 8 . what are the top 3 most purchased products whithin each category?
with item_counts as (
select category , item_purchased, 
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;


-- --> 9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id)as repeat_buyers
from customer_shopping 
where previous_purchases >5 
group by subscription_status;


-- --> 10 what is the revenue contribution of each age group ?
select count(customer_id), age ,sum(purchese_amount) as "total_revenue_by_age"
from customer_shopping 
group by age
order by age;



select count(customer_id), age_group ,sum(purchese_amount) as "total_revenue_by_age_group"
from customer_shopping 
group by age_group
order by age_group;